### ISSUE TITLE
Document deepbills

### ISSUE THREAD

**Issue by JoshData** [unitedstates/congress#115]
splitting this out from #90 

at https://github.com/unitedstates/congress/wiki/bill-text

**Comment by treymo** [comment]
Do you think it's worth just dropping the deepbills stuff?  There is only data for the 113th congress and it appears there hasn't been activity in at least a couple years.

https://groups.google.com/forum/?fromgroups#!topic/cato-government-transparency-data/0zJYwAy-ve4
