### ISSUE TITLE
Nomination Scraper issue?

### ISSUE THREAD

**Issue by LindsayYoung** [unitedstates/congress#136]
I keep getting an error in nomination_info.py, line 204. This showed up for me 3 days ago, is anyone else having an issue with it?  

My guess is that the page changed slightly. I am looking into it. 

```
Traceback (most recent call last):

  File "tasks/utils.py", line 173, in process_set
    results = fetch_func(id, options, *extra_args)

  File "tasks/nomination_info.py", line 57, in fetch_nomination
    nomination = parse_nomination(nomination_id, body, options)

  File "tasks/nomination_info.py", line 204, in parse_nomination
    raise Exception("Choked, couldn't find nominee info.")
```

**Comment by crdunwel** [comment]
Scraper being written for congress.gov which may resolve this issue. See https://github.com/unitedstates/congress/issues/173

**Comment by JoshData** [comment]
Closing b/c of #173.
