### ISSUE TITLE
bill action missing data found on Thomas

### ISSUE THREAD

**Issue by predict-r** [unitedstates/congress#145]
According to the wiki, bill actions  should include information about the committee they occurred in.

>If the action occurs in a committee, the action object will also have:
>in_committee: The committee in which the activity occurred. It is the full committee name.
>in_subcommittee: The committee in which the activity occurred. It is the subcommittee's name.

On Thomas and Congress.gov (e.g. 107hr5005), this indeed is the case. The action of "Committee Hearings" occurs *within* a committee as indicated by the indention:

>6/24/2002:
>Referred to House Homeland Security (Select)
>>    7/15/2002:
>>   Committee Hearings Held.

http://thomas.loc.gov/cgi-bin/bdquery/z?d107:HR05005:@@@S

The congress.gov site is also specific about which committee held the hearing:
https://beta.congress.gov/bill/107th-congress/house-bill/5005/all-actions-with-amendments?pageSort=asc

Yet, looking at the govtrack data in govtrack.us/data/congress/, which is a mirror of this project as I understand it, there is no information about where the committee hearings were actually held:

<action datetime="2002-07-15">
<text>Committee Hearings Held.</text>
</action>
<action datetime="2002-07-16">
<text>Committee Hearings Held.</text>
</action>
<action datetime="2002-07-17">
<text>Committee Hearings Held.</text>
</action>

https://www.govtrack.us/data/congress/107/bills/hr/hr5005/data.xml

Is there a way to tweak a script to get this data included? What are the options?

**Comment by JoshData** [comment]
Closing because the new upstream XML data handles this differently and the issue would need to be re-investigated. See #175.
