### ISSUE TITLE
Add source url in bill_info scraper output

### ISSUE THREAD

**Issue by crdunwel** [unitedstates/congress#157]
See https://github.com/crdunwel/congress/commit/81bc022dfa163ec82b329ef16fa64e8c87df8e65

The source url is present in some of the other scrapers (votes, bill_versions) and so it would also be nice to be present in the bill_info scraper as well.

I realize my pull request doesn't handle the split case. For robustness, we could make it so the url key maps to a dictionary of types (amendments, committees, related_bills, etc, etc) with the explicit URL for each, but that would create a lot of unnecessary redundancy. There are pros/cons to either way so let me know what you all think is best.

**Comment by handlers** [comment]
Definitely in support of adding this information. I think the THOMAS url is sufficient as a source.

**Comment by handlers** [comment]
closed here 81bc022
