### ISSUE TITLE
Heterogeneous JSON data in Historical Vote Array (Vice President)

### ISSUE THREAD

**Issue by vadvv** [unitedstates/congress#161]
Hi,
I looked for this in previous posts and didn't find anything on it, but I apologize in advance if this was already discussed (in which case, I'd appreciate if someone could point me to the thread).

I found invalid JSON data when parsing votes for historical purposes. I found a vote with the body "VP" in it instead of the standard expected object. This was in a few votes in 106th and the 107th Congress (so far). I think it is in instances where the Vice President casts the tie-breaking vote in the US Senate.

An example is in these files (links from GovTrack):
https://www.govtrack.us/data/congress/106/votes/1999/s134/data.json
https://www.govtrack.us/data/congress/107/votes/2001/s65/data.json
https://www.govtrack.us/data/congress/107/votes/2001/s79/data.json
https://www.govtrack.us/data/congress/107/votes/2002/s119/data.json

I was wondering if this could perhaps be handled more gracefully, but putting in the VP's infor like the other legislators' information.

**Comment by JoshData** [comment]
At the least we should get it documented. https://github.com/unitedstates/congress/wiki/votes

Generally I don't like change. It's not invalid --- just ugly. If we change it, everyone that uses this data has to go update their code (and I am lazy!).

**Comment by vadvv** [comment]
Thanks for responding. You're right. It's not "Invalid". I'll change the subject. I can relate that once it's out in the wild, it's had to correct. I'll adapt my code as well.
