### ISSUE TITLE
Mongodump?

### ISSUE THREAD

**Issue by ccorcos** [unitedstates/congress#164]
It would be awesome if all this data were imported into a mongodb instance and dumped so I can just download the data, and `mongorestore` so I can play with it all...

https://docs.mongodb.org/manual/reference/program/mongodump/

**Comment by JoshData** [comment]
If you write a script to perform the dump, I'll run it (daily) and make the results available.

**Comment by ccorcos** [comment]
Awesome. Sounds like a plan

**Comment by ccorcos** [comment]
@JoshData I could use some help with this... finally getting around to it again. 

What I want is to run a command to get all the voting data from the last decade in JSON format

**Comment by JoshData** [comment]
See https://github.com/unitedstates/congress/wiki/votes, but you should be getting JSON as well as XML, side by side.
