### ISSUE TITLE
More docs please :)

### ISSUE THREAD

**Issue by ccorcos** [unitedstates/congress#166]
What is a cloture vs passage vs amendment?

Also, I'm seeing things like this for voting... why isn't it just yes and no?

[u'No', u'Aye', u'Yea', u'Present', u'Nay', u'Not Voting']

**Comment by crdunwel** [comment]
Welcome to the wild world of government data. [This blog post](https://www.govtrack.us/blog/2009/11/18/aye-versus-yea-whats-the-difference/) may help explain why votes aren't simply "yes" or "no". If you haven't already, hop over to the [wiki](https://github.com/unitedstates/congress/wiki) to get more documentation for this project.

**Comment by ccorcos** [comment]
Jesus... this country... lol. Thanks for the pointers.

I'd really like to help organize this more. I think it would be amazing if we used something like Datomic so we can run very expressive graph queries... What do you think?

**Comment by crdunwel** [comment]
Have at it!. This project just scrapes and gathers data for the US Congress and is licensed under (CC0 1.0 Universal)[https://creativecommons.org/publicdomain/zero/1.0/]. Most of those who support this project also consume it such as [GovTrack](https://www.govtrack.us/developers/data) and [Sunlight's Congress API](https://sunlightlabs.github.io/congress/). If you wish to build more powerful querying tools on top of the data then feel free!
