### ISSUE TITLE
anyone using bill_versions.py?

### ISSUE THREAD

**Issue by JoshData** [unitedstates/congress#169]
We have a script called `bill_versions` that fetches bill text from GPO, by fetching any bill text files that are not yet downloaded. It shares some code with `fdsys`, which downloads bill text files according to what's changed in GPO's sitemaps.

Is anyone using `bill_versions`? It appears to have been broken for a few months --- since GPO switched to https (a regex wasn't updated).

If no one is using it, I'd like to delete it as a part of cleaning up the `fdsys` scraper (see #165), and so we have one scraper for downloading bill text rather than two.

**Comment by konklone** [comment]
I wrote `bill_versions.py`, but I don't think I ever switched Sunlight's Congress API over to using it. I've looked over what Sunlight appears to be using for its Congress API:

https://github.com/sunlightlabs/congress/search?utf8=%E2%9C%93&q=bill_versions
https://github.com/sunlightlabs/congress/tree/master/config/cron/scripts

And I do not see `bill_versions` being used anywhere. The role of spidering over GPO's sitemaps is performed by a Ruby script (which could also use an update for `https://` URLs for GPO):

https://github.com/sunlightlabs/congress/blob/master/tasks/bills_bulk/bills_bulk.rb

But @crdunwel would, I think, be the person to confirm this.

**Comment by JoshData** [comment]
Ok, closing - script will be removed in #170 / #175 on merge.
