### ISSUE TITLE
Found this useful hope it helps

### ISSUE THREAD

**Issue by neilmartis** [unitedstates/congress#171]
@konklone I found done by a friend of mine using neo4j http://neo4j.com/blog/geospatial-indexing-us-congress-neo4j/  can you check it out since its related to congress

**Comment by konklone** [comment]
Hi @neilmartis, thanks for sending this, but I'd prefer for inquiries like this you send them by email to eric@konklone.com, so as not to unnecessarily email the watchers of this repository.
