### ISSUE TITLE
Archive the old THOMAS pages so we have a reference for historical data

### ISSUE THREAD

**Issue by JoshData** [unitedstates/congress#174]
We should save an archive of the HTML pages of THOMAS so we have a reference for historical data, in case we need to scrape it again.

**Comment by DanielSchuman** [comment]
Agree with this entirely. It's also helpful to put this suggestion on the
GPO/LOC's github page so they archive it too.

**Comment by JoshData** [comment]
I've re-run my THOMAS scraper over all its data so I now have an archive.

**Comment by DanielSchuman** [comment]
Thank you for doing that, Josh. It's important that we have a final copy,
just in case. :)
