### ISSUE TITLE
Exceptions. Crawler is not working at all. It throws exception and did not download enything.

### ISSUE THREAD

**Issue by veselins** [unitedstates/congress#177]
Hello, 

Since thomas shuttdown, the crawler did not download enything. Just throws the following exceptions. If there is no exceptions it doesn't save anything.

Any ideas!!

Command used to start crawler is:

`**./run bills --congress=114 --force**`

> [s754-114] Exception:
> 
> Traceback (most recent call last):
> 
>   File "/LegCyteTools/congress-master/tasks/utils.py", line 173, in process_set
>     results = fetch_func(id, options, *extra_args)
> 
>   File "/LegCyteTools/congress-master/tasks/bills.py", line 109, in process_bill
>     process_amendments(bill_id, xml_as_dict, options)
> 
>   File "/LegCyteTools/congress-master/tasks/bills.py", line 216, in process_amendments
>     amendment_info.process_amendment(amdt, bill_id, options)
> 
>   File "/LegCyteTools/congress-master/tasks/amendment_info.py", line 13, in process_amendment
>     amdt = build_amendment_json_dict(amdt_data, options)
> 
>   File "/LegCyteTools/congress-master/tasks/amendment_info.py", line 36, in build_amendment_json_dict
>     amends_bill = amends_bill_for(amdt_dict.get('amendedBill'))  # almost always present
> 
>   File "/LegCyteTools/congress-master/tasks/amendment_info.py", line 146, in amends_bill_for
>     bill_id = build_bill_id(amends_bill['type'].lower(), amends_bill['number'], amends_bill['congress'])
> 
> TypeError: 'NoneType' object has no attribute '__getitem__'
> 
> 
> [s2943-114] Exception:
> 
> Traceback (most recent call last):
> 
>   File "/LegCyteTools/congress-master/tasks/utils.py", line 173, in process_set
>     results = fetch_func(id, options, *extra_args)
> 
>   File "/LegCyteTools/congress-master/tasks/bills.py", line 109, in process_bill
>     process_amendments(bill_id, xml_as_dict, options)
> 
>   File "/LegCyteTools/congress-master/tasks/bills.py", line 216, in process_amendments
>     amendment_info.process_amendment(amdt, bill_id, options)
> 
>   File "/LegCyteTools/congress-master/tasks/amendment_info.py", line 13, in process_amendment
>     amdt = build_amendment_json_dict(amdt_data, options)
> 
>   File "/LegCyteTools/congress-master/tasks/amendment_info.py", line 72, in build_amendment_json_dict
>     amdt['proposed_at'] = amdt_dict['proposedDate']
> 
> KeyError: 'proposedDate'
>

**Comment by JoshData** [comment]
See #175 and the updated bills documentation on the wiki of this repository, please.
