### ISSUE TITLE
HJRES 10 Active = True & Enacted = True

### ISSUE THREAD

**Issue by abhisuri97** [unitedstates/congress#181]
For HJRES 10: 
I noticed under 'history' it has an active value of true and enacted value of true. Correct me if I am wrong, but isn't a bill that is enacted no longer being discussed in congress (aka not active). If so, why does this appear to be the case?

**Comment by abhisuri97** [comment]
Link for reference

https://www.govtrack.us/data/congress/114/bills/hjres/hjres10/data.json

**Comment by JoshData** [comment]
See https://github.com/unitedstates/congress/wiki/Bills for documentation for the field.
