### ISSUE TITLE
Missing fields in converting bills from XML to JSON

### ISSUE THREAD

**Issue by krues8dr** [unitedstates/congress#183]
While running `./run bills` on data from the 113th & 114th, I'm getting a lot of key errors:

```
[sres259-114] Exception:

Traceback (most recent call last):

  File "/Users/krues8dr/Sites/congress/tasks/utils.py", line 173, in process_set
    results = fetch_func(id, options, *extra_args)

  File "/Users/krues8dr/Sites/congress/tasks/bills.py", line 97, in process_bill
    bill_data = form_bill_json_dict(xml_as_dict)

  File "/Users/krues8dr/Sites/congress/tasks/bills.py", line 174, in form_bill_json_dict
    'subjects_top_term': _fixup_top_term_case(bill_dict['policyArea']['name']) if bill_dict['policyArea'] else None,

KeyError: 'policyArea'
```

(this is repeated a hundred times.)

The problem lies in the `if` clause which is evaluating `bill_dict['policyArea']` – resolving that, I see it again on `billSubjects`.  To test if the value exists, I think `.has_key` might be preferable here?  

I'll send over a PR for how I resolved this.

**Comment by JoshData** [comment]
I'm not getting this error. You might need to re-run the fdsys script to pull down new XML first. GPO changed the schema spontaneously recently.

**Comment by krues8dr** [comment]
This is from a fresh install, just ran fdsys last night?

**Comment by krues8dr** [comment]
( `./run fdsys --collections=BILLSTATUS --years=2015,2016` )

**Comment by JoshData** [comment]
Maybe the `xmltodict` dependency changed and I'm running an earlier version...

**Comment by krues8dr** [comment]
There's my proposed fix, but I'm not sure if this actually fixes it or mangles the data in some unforeseen way, since I haven't run it against anything but my specific use case - and I don't know 100% what it _should_ have looked like necessarily aside from guessing.

**Comment by JoshData** [comment]
This seems like an upstream data issue. The [file](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/114/sres/BILLSTATUS-114sres259.xml) has reverted to the schema in use prior to https://github.com/usgpo/bill-status/issues/25.

**Comment by krues8dr** [comment]
Ok, I can redo my fix to search there instead?

**Comment by JoshData** [comment]
Interestingly, the file contents changed even though the sitemap doesn't list an update --- which is why I wasn't seeing the problem.

**Comment by JoshData** [comment]
No I think the solution is to complain to USGPO and leave the scrapers as correctly identifying a problem.

**Comment by krues8dr** [comment]
:+1: Ok.

**Comment by JoshData** [comment]
I added a comment to the USGPO issue that I linked to above. We can leave this issue open till that's resolved.

**Comment by JoshData** [comment]
It was resolved a while ago so closing.
