### ISSUE TITLE
PyPi package available?

### ISSUE THREAD

**Issue by illegalnumbers** [unitedstates/congress#188]
Hey there!

This looks like it is a great project. I was wondering if it was packaged in PyPi or somewhere so I can import it into my django project without directly cloning the repository. If not I could package it up and get that up and running, although admittedly I am relearning Python after an extended absence.

**Comment by JoshData** [comment]
Hi @illegalnumbers. Thanks. It's not. And while I see the upside to better packaging, it also requires a little more effort in maintenance (proper versioning, updating pypi) which I don't think anyone here has the time to commit to it.

**Comment by illegalnumbers** [comment]
Thanks for the response!

What do you mean by 'updating pypi'?

As for versioning - it could be as simple as semantic versioning, no?

**Comment by JoshData** [comment]
> What do you mean by 'updating pypi'?

Posting new updates to pypi.

> it could be as simple as

Everything takes time.

**Comment by illegalnumbers** [comment]
Can't travis do those things for you automatically?

https://docs.travis-ci.com/user/deployment/pypi/

As for versioning it could be done as easily as pushing up a git tag on build as well.

**Comment by konklone** [comment]
@illegalnumbers Any way you could help us along with a pull request that sets up the necessary edits to `.travis.yml` for us to test out?

**Comment by illegalnumbers** [comment]
Yea sure! I will be incapacitated all week this week due to surgery but after I start feeling better I'd be fine with doing a pull request.

**Comment by illegalnumbers** [comment]
So while building the `setup.py` for PyPi to work I need an email address associated with the maintainer of the package...is there something specific I should use there? For the example they show just using a googlegroup or something so it doesn't have to be a direct line to anyone.

**Comment by illegalnumbers** [comment]
Additionally - pip provides `entry_points` as an alternative to having scripts in your package that are runnable. Would it be preferentially to port the commands from the script directory to various entry_points since it's platform independent? I could try and get that up too.

**Comment by illegalnumbers** [comment]
[Just to show progress.](https://pypi.python.org/pypi/united-states-congress) If anyone wants like owner access or whatever let me know and I can grant it. I need to do some fiddling with my local repo before opening a PR. I had to use 'united-states-' since 'congress' was already taken.

**Comment by illegalnumbers** [comment]
Well after toying with this for days I can see why you didn't just use PyPi to begin with. The setup of this is incredibly poor and makes me grateful I write Ruby for a living. Still trying to figure out why some dependencies don't get installed, are missing from certain repo's in a test environment, etc.

**Comment by illegalnumbers** [comment]
Seems I'm getting nowhere with the test PyPi package. It works when you install from prod PyPi so I'm going to leave it at that for now.

Someone test this out for me if you will `pip install united-states-congress`

Pull request incoming for this.

**Comment by acxz** [comment]
@JoshData can this issue be closed in favor of #282

**Comment by JoshData** [comment]
@illegalnumbers Hey. I pinged you on Twitter about taking over the pypi package. (I completely forgot about this issue.) Hope to hear back (there or here or in #282). Thanks.
