### ISSUE TITLE
sudo pip install is wrong

### ISSUE THREAD

**Issue by GoldenJoe** [unitedstates/congress#195]
Or at least that's what I found when I researched an error message when I tried to use it:
http://stackoverflow.com/questions/33004708/osx-el-capitan-sudo-pip-install-oserror-errno-1-operation-not-permitted/33004920#33004920

**Comment by JoshData** [comment]
Where are we recommending using `sudo pip install`?

**Comment by meli-lewis** [comment]
https://github.com/unitedstates/congress/blob/master/README.md#setting-up

**Comment by konklone** [comment]
Thanks for flagging this, @GoldenJoe and @meli-lewis. I filed #200 to fix it.
