### ISSUE TITLE
[Question] Support and updates after August 2017

### ISSUE THREAD

**Issue by conmarap** [unitedstates/congress#199]
Since the bulk data API on govtrack will be deprecated this summer, does this mean that support and updates will stop for this repo, `congress-legistators`, etc? Or will Congress use the same JSON format for their bulk data?

Sorry if this question has been raised before, but I couldn't find an answer.

**Comment by JoshData** [comment]
This repo is maintained by lots of folks besides GovTrack (me), so it'll go on unaffected.

**Comment by conmarap** [comment]
Perfect. Thank you for the answer!
