### ISSUE TITLE
Why do senators use lis ID while house members use bioguide ID in Votes?

### ISSUE THREAD

**Issue by GoldenJoe** [unitedstates/congress#205]
It's not a huge inconvenience, but why are senators and house members using different IDs in Votes? Senators have a bioguide ID, and it's always better to keep things consistent. Maybe senate vote records could distinguish between "id" (bioguide) and "id_lis" (lis)?

**Comment by JoshData** [comment]
These are the IDs that appear in the source data. The Senate publishes votes using lis_id and the House using bioguide IDs.

**Comment by GoldenJoe** [comment]
Do you have any idea why they do that? I'm under the impression that bioguide is kind of a primary ID that replaced THOMAS. Why would they only report lis?

**Comment by dwillis** [comment]
Because the Senate does what it likes, basically.

**Comment by GoldenJoe** [comment]
Haha, of course. So in a perfect world, would you have them use bioguide for everything, and if not why? I'm working on a way to make a DB of this data.

**Comment by JoshData** [comment]
You've asked a question that doesn't really have an answer. There are a variety of (somewhat obvious) reasons why having two ID systems might be useful, and we're not the only stakeholders for this data so there are likely many other good reasons that we're not privy to. It is what it is.
