### ISSUE TITLE
Passed bills have "Unknown" status tag in XML

### ISSUE THREAD

**Issue by pqnelson** [unitedstates/congress#208]
I noticed this morning some errors running the bill task, they all look like:

```python
[s544-115] Exception:

Traceback (most recent call last):

  File "/home/anelson/unitedstates/congress/tasks/utils.py", line 173, in process_set
    results = fetch_func(id, options, *extra_args)

  File "/home/anelson/unitedstates/congress/tasks/bills.py", line 102, in process_bill
    bill_data = form_bill_json_dict(xml_as_dict)

  File "/home/anelson/unitedstates/congress/tasks/bills.py", line 159, in form_bill_json_dict
    'by_request': bill_dict['sponsors']['item'][0]['byRequestType']     is not None,

TypeError: 'NoneType' object has no attribute '__getitem__'
```

Examining the `data.xml` file for s544-115 (and the other 4 or 5 problematic bills), they look like:

```xml
<bill session="115" type="s" number="544" updated="2017-04-07T11:55:41Z">
  <state datetime="2017-04-05T14:42:49-04:00">PASSED:BILL</state>
  <status>
    <unknown datetime="2017-04-05T14:42:49-04:00"/> <!-- THIS IS CAUSE OF ERROR -->
  </status>
  <!-- snip -->
</bill>
```

I first crawled using the fdsys task with `--bulkdata=True`, but even with `--bulkdata=False` I get the same errors.

**Comment by JoshData** [comment]
> TypeError: 'NoneType' object has no attribute '__getitem__'

This is an upstream data problem at GPO: https://github.com/usgpo/bill-status/issues/38

> Examining the data.xml file for s544-115 (and the other 4 or 5 problematic bills), they look like:

That's actually unrelated. The XML format output was mostly for me and I don't think we intend to keep supporting it (see #191). The `status` node is there for compatibility and has never been implemented, as far as I remember. You should stick to the JSON format and what's documented [on the wiki](https://github.com/unitedstates/congress/wiki/Bills).

**Comment by pqnelson** [comment]
@JoshData Thanks for the quick reply. I dimly remembered a similar problem with 114 bills, but then convinced myself (wrongly) this was something new.
