### ISSUE TITLE
How will things change when GovTrack goes away in the fall?

### ISSUE THREAD

**Issue by BogusException** [unitedstates/congress#212]
Team,

You still mention govtrack.us as active in the docs here. I'm wondering if their leaving will impact anything, is all.

I'm working to bring this data into C# classes, so if you hear of anyone else doing this, I'd love to know! :) I want to use the data in a windows C#.NET app, is why. 

Thanks for your great work!

"In 2016, after a 15-year campaign, we finally convinced the U.S. Congress to make legislative data available themselves directly. The ecosystem of non-governmental open data providers has also completely changed since 2005. As a result, we deprecated our raw bulk data and APIs in 2016 with a scheduled shut-off date of August 2017." [source](https://www.govtrack.us/developers)

**Comment by JoshData** [comment]
GovTrack isn't going anywhere. We're discontinuing our raw data and API because they are now redundant with this project and the ProPublica API. But GovTrack itself will go on as usual, and I'll still be committing here because these are the scripts we run to get the data we display on the site.

**Comment by BogusException** [comment]
Thanks for writing, Josh...
Oh! Well, that doesn't sound as 'doom & gloom' as it reads on the site, then!

[_Unrelated/unsolicited taking advantage of this communique_]: I'm trying to find a way to parse your work into C# classes, and have come close, but there always seems to be a gotcha. Does any other project or person come to mind that is parsing the output of your work in such a way? I feel like I've tried creating classes from XML & JSON a bunch of ways, but none get the job done. Many thanks for any leads!@ :)

Feel free to delete this question, as I am ignorant of any other way to ask, and it certainly isn't a bug by any stretch! :)

**Comment by BogusException** [comment]
Josh,
Thanks for writing. I really appreciate it.

So where should I go to grab the data in JSON/XML format? Is there a way to
grab it post-parser? I ask because I am having nothing but problems getting
the scripts to work-even in a clean VM, as presented here... (ex:
congress *here
<https://github.com/unitedstates/congress>*) :(

I'm ultimately trying to just get the data into C# objects, then stored to
DB using EF (Entity Framework)... I've written web scrapers in the past
(Plucker), but I'm struggling to understand whether I even need to if I can
find post-parsed data from the top level sites.

Any guidance/suggestions appreciated. I'm running in circles at this point,
mentally exhausted after weeks of trying anything at random
unsuccessfully... :(

Thanks!

pat
:)

**Comment by JoshData** [comment]
> Does any other project or person come to mind that is parsing the output of your work in such a way?

Well several of us (GovTrack, ProPublica) do. If you have specific questions, feel free to start a new issue!

> So where should I go to grab the data in JSON/XML format? Is there a way to grab it post-parser?

Right now no one is offering that. You could go straight to the source data (GPO, House, Senate, etc.).

The best thing is to help us get these scripts into a better place where it works for you and everyone.
