### ISSUE TITLE
requirements.txt error2

### ISSUE THREAD

**Issue by CrispinOwuor** [unitedstates/congress#217]
Hi guys, i seem to be haing an issue with the requirements txt when i try to pip install -r requirements.txt. ive set up a virtual environment in ubuntu as planned, and also i would like to know how to inject the code like bills.py on the python environment. and also do i source the bash within the encironment or outside? Your assistance is kindly appreciated.

**Comment by JoshData** [comment]
What problem are you running into when running the pip command?

**Comment by CrispinOwuor** [comment]
Hallo JoshData, thanks for replying, i was able to sort the issue, it seems i didnt put all the files in one folder, i was able to run the requirements package and also was able to run the bills script and task. It seems i just didnt read the documentation properly, now im currently waiting patiently lol
![virtualbox_ubuntu_27_06_2017_23_54_20](https://user-images.githubusercontent.com/29709521/27640288-da2db38c-5be6-11e7-9ea9-92d175c95cd1.png)

**Comment by CrispinOwuor** [comment]
One last question, do you guys have a tutorial on making a database in regards to the data? i would really appreciate it.

**Comment by avbanks** [comment]
You need to exclude ".py" just run fdsys.
