### ISSUE TITLE
Sitemap URLs Changed

### ISSUE THREAD

**Issue by lwaltman** [unitedstates/congress#235]
@JoshData It appears that the base URL for the FDSys sitemaps has changed - and possibly other changes, too.  For this reason, you can no longer get any bill updates with the scrapers.

Are there a whole slew of changes that have come down as a result of whatever govinfo.gov is instead of gpo?

**Comment by JoshData** [comment]
Hi. Have you seen the changes from #229?

**Comment by lwaltman** [comment]
Thank you.  I was still using the old FDSys script, as I had not kept track of all of these changes, and they hit unexpectedly in the New Year.  I will update this thread if I find that anything is out of place.

**Comment by JoshData** [comment]
Great. Let me know. I spent a lot of time on the update so I hope you can put it to use too. :)

**Comment by lwaltman** [comment]
Have you encountered anything like this error?

[2019-01-13 18:00:01-06:00]: Begin updating bills from GovInfo.
Downloading: https://www.govinfo.gov/sitemap/bulkdata/BILLSTATUS/sitemapindex.xml
Downloading: https://www.govinfo.gov/sitemap/BILLS_sitemap_index.xml
Traceback (most recent call last):

  File "./run", line 71, in <module>
    task_mod.run(options)

  File "/home/lwaltman/cicero/static/congress/tasks/govinfo.py", line 72, in run
    for collection in sorted(options.get("bulkdata", "").split(",")):

AttributeError: 'bool' object has no attribute 'split'

I started getting it after i updated to the new govinfo script in a script I call every six hours:
`log "Begin updating bills from GovInfo."
./run govinfo --bulkdata=BILLSTATUS
./run govinfo --collections=BILLS --congress=113 --extract=pdf,xml,text --bulkdata=False
./run govinfo --collections=BILLS --congress=114 --extract=pdf,xml,text --bulkdata=False
./run govinfo --collections=BILLS --congress=115 --extract=pdf,xml,text --bulkdata=False
./run govinfo --collections=BILLS --congress=116 --extract=pdf,xml,text --bulkdata=False`

**Comment by JoshData** [comment]
Hi.

With the changes, `--bulkdata=False` is no longer an option --- for BILLS, you just omit it.
