### ISSUE TITLE
Running govinfo.py fails on line 72

### ISSUE THREAD

**Issue by John-Ingles-gitH** [unitedstates/congress#240]
I issued the command `./run govinfo --collections=BILLS --congress=112 --store=pdf,mods,xml,text --bulkdata=False` from the terminal and received the error on line 72 of govinfo.py.  The issue is that the split function is being called on options.get("bulkdata", "") but the options dict only has 1 value for bulkdata which is FALSE as I put in the terminal command.  I'm not sure why this code would have worked in the first place since it looks like it will always fail. What am I missing?

**Comment by JoshData** [comment]
Someone put in incorrect documentation on the wiki. See the top of the govinfo.py script for how to run it: https://github.com/unitedstates/congress/blob/master/tasks/govinfo.py

**Comment by John-Ingles-gitH** [comment]
Ok, should I just leave the bulkdata line out of the command if I don't want it then?

**Comment by JoshData** [comment]
Yup!

**Comment by kkloste** [comment]
I ran into the exact same problem from looking at the wiki on 6/29/2019 --- it seems like the documentation should be changed?
The new command suggested here worked for me (thank you JoshData!)
