### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by mikeshyavitzcbo** [unitedstates/congress#241]
Hi All - We're getting a 500 when making calls to the API. Just wanted to report. Any idea when it will be back up? 

Thanks,
Mike

**Comment by dwillis** [comment]
Should be back now - you can report errors [here](https://github.com/propublica/congress-api-docs/issues)

**Comment by mikeshyavitzcbo** [comment]
Great. Will use that link in the future. 

Thanks,
Mike
