### ISSUE TITLE
bill_info task encounters `KeyError: 'committee'`

### ISSUE THREAD

**Issue by pqnelson** [unitedstates/congress#245]
I noticed the crawler is having issues with 881 bills in the 116th congress, I'm constantly getting errors of the form:

```
~/unitedstates/congress/$ run bills --congress=116
...
[sres455-116] Exception:

Traceback (most recent call last):

  File "/home/anelson/unitedstates/congress/tasks/utils.py", line 174, in process_set
    results = fetch_func(id, options, *extra_args)

  File "/home/anelson/unitedstates/congress/tasks/bills.py", line 102, in process_bill
    bill_data = form_bill_json_dict(xml_as_dict)

  File "/home/anelson/unitedstates/congress/tasks/bills.py", line 147, in form_bill_json_dict
    actions = bill_info.actions_for(bill_dict['actions']['item'], bill_id, bill_info.current_title_for(titles, 'official'))

  File "/home/anelson/unitedstates/congress/tasks/bill_info.py", line 403, in actions_for
    if keep_action(item, closure)]

  File "/home/anelson/unitedstates/congress/tasks/bill_info.py", line 396, in keep_action
    and action_for(item)['text'].replace(" ", "").endswith(action_for(closure["prev"])['text'].replace(" ", "")):

  File "/home/anelson/unitedstates/congress/tasks/bill_info.py", line 485, in action_for
    'committees': [item['committee']['systemCode'][0:-2].upper()] if item['committee'] else None,

KeyError: 'committee'

Errors for 881.
Skipped 0.
Saved data for 9054.
```

This is with the latest version of the code (I did a `git pull --rebase` before running this command) and having all the requirements installed (I ran `workon congress` right before running this command).

**Comment by pqnelson** [comment]
I noticed changing line 485 of `bill_info.py` to be `'committees': [item['committee']['systemCode'][0:-2].upper()] if 'committee' in item else None,` produces a new problem, namely `TypeError: 'NoneType' object has no attribute '__getitem__'`.

**Comment by JoshData** [comment]
I'm getting this too. Haven't had a chance to debug yet, unfortunately.

**Comment by dsal1951** [comment]
If you are looking for a specific bill to debug: 

`./run bills --log=debug --bill_id=hr3172-116`

To be clear though, this is just one of many that I'm getting this error on

**Comment by dwillis** [comment]
It looks to me that in at least some of the XML files that `committee` in the `actions` list has been changed to `committees`, although I have not found yet if that means that multiple committees could be listed in a single action.

**Comment by JoshData** [comment]
I think it's related to this: https://github.com/usgpo/bill-status/issues/147

**Comment by JoshData** [comment]
PR at #246. Starting next week I'll be on vacation for a while, so if there's an issue with the PR, I may not be able to participate.

**Comment by JoshData** [comment]
GPO says on the linked issue that they will reprocess the files to put the tag back to `<committee/>` until formally rolling out the change.

**Comment by jonquandt** [comment]
Hi, all -- we implemented a fix to prevent the issue from recurring prior to the actual rollout of the change. 

[HR3](https://www.govinfo.gov/bulkdata/BILLSTATUS/116/hr/BILLSTATUS-116hr3.xml) has been reprocessed and BILLSTATUS packages from ~4:45pm today should all have the correct `committee` element. We are working on reprocessing the remaining affected files and I will provide an update here and on the linked https://github.com/usgpo/bill-status/issues/147 issue when those are complete. 

We appreciate your patience.

**Comment by jonquandt** [comment]
All affected billstatus packages were reprocessed by the end of last week.
