### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by demongolem** [unitedstates/congress#256]
When I run `./run bills` I get `test.test_support.ResourceDenied: Use of the `urlfetch' resource not enabled`.  This is a fatal error.

**Comment by demongolem** [comment]
Ah, I see, the run script points to Python 2 whereas I uses Python 3 for everything.  When I make this replacement in the run file, things run.  But overall, what support is there for Python3?

**Comment by dwillis** [comment]
@demongolem There is a `python3` branch, but it has not been active for some time. If you'd like to get involved, we'd welcome your participation.

**Comment by konklone** [comment]
Not finishing the Python 3 port before leaving Sunlight was my greatest regret for this project - it's old enough (~2014) that it probably needs a fresh start.

**Comment by stevesdawg** [comment]
Hello, I began the porting process from Python 2 to Python 3.
First PR is here: #263 
More PR's to follow addressing the more advanced compatibility issues.

**Comment by danieldjewell** [comment]
For sure this has been changed in 3.x:

https://github.com/unitedstates/congress/blob/f327c0af85eec11886178db7aaa7d6d599087a24/tasks/utils.py#L9

I wonder how 2to3 works ....

**Comment by acxz** [comment]
@JoshData I believe we can now close this issue with #265 being merged in.
