### ISSUE TITLE
Newbie Q: Pulling bills for only one topic

### ISSUE THREAD

**Issue by heatherredwards** [unitedstates/congress#268]
Thank you all so much for the work that you do on this project! I've been a member of this repository for a long time, and I am finally jumping in! (or trying to)

I am teaching myself how to build a data set for congressional bill data, and I need a little help getting started. I only want to pull data for bills that include the terms "child welfare" and/or "foster care". 

If I were collecting this data from Congress.gov, I would conduct one search for each term and merge the data. 

Is there a way to use this GitHub code to only pull the bills in which I am interested? Or do I need to conduct a Congress.gov search, and use the bill numbers from that search to conduct individual searches for each bill (e.g., ./run bills --bill_id=s968-112)?  Thank you so much for helping me get get some momentum on my project!

**Comment by JoshData** [comment]
It might be possible to make some modifications to do it, but it's probably not worth your time to figure it out. It'll be easier to download all of the bill data and then only look at relevant bill files, or scan those files for the subject terms to figure out which files are relevant.

On November 25, 2020 9:05:27 AM EST, heatherredwards <notifications@github.com> wrote:
>Thank you all so much for the work that you do on this project! I've
>been a member of this repository for a long time, and I am finally
>jumping in! (or trying to)
>
>I am teaching myself how to build a data set for congressional bill
>data, and I need a little help getting started. I only want to pull
>data for bills that include the terms "child welfare" and/or "foster
>care". 
>
>If I were collecting this data from Congress.gov, I would conduct one
>search for each term and merge the data. 
>
>Is there a way to use this GitHub code to only pull the bills in which
>I am interested? Or do I need to conduct a Congress.gov search, and use
>the bill numbers from that search to conduct individual searches for
>each bill (e.g., ./run bills --bill_id=s968-112)?  Thank you so much
>for helping me get get some momentum on my project!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/unitedstates/congress/issues/268

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by heatherredwards** [comment]
> 
> It might be possible to make some modifications to do it, but it's probably not worth your time to figure it out. It'll be easier to download all of the bill data and then only look at relevant bill files, or scan those files for the subject terms to figure out which files are relevant.
> […](#)
> On November 25, 2020 9:05:27 AM EST, heatherredwards ***@***.***> wrote: Thank you all so much for the work that you do on this project! I've been a member of this repository for a long time, and I am finally jumping in! (or trying to) I am teaching myself how to build a data set for congressional bill data, and I need a little help getting started. I only want to pull data for bills that include the terms "child welfare" and/or "foster care". If I were collecting this data from Congress.gov, I would conduct one search for each term and merge the data. Is there a way to use this GitHub code to only pull the bills in which I am interested? Or do I need to conduct a Congress.gov search, and use the bill numbers from that search to conduct individual searches for each bill (e.g., ./run bills --bill_id=s968-112)? Thank you so much for helping me get get some momentum on my project! -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #268
> -- Sent from my Android device with K-9 Mail. Please excuse my brevity.

Thank you!!!
