### ISSUE TITLE
Error: ImportError: No module named html.entities after the Feb 28th update

### ISSUE THREAD

**Issue by jacobcrp** [unitedstates/congress#271]
Morning!

Running into this error after pulling in the newest changes from Feb 28th:

```
./run govinfo --bulkdata=BILLSTATUS
Traceback (most recent call last):
  File "./run", line 54, in <module>
    import utils
  File "/home/ubuntu/congress3/congress/tasks/utils.py", line 9, in <module>
    import html.entities
ImportError: No module named html.entities
```

This box is only used for pulling in Bills data but it's possible there was an update to the OS I don't know about that could have thrown a wrench into our processing.

Thanks!

**Comment by JoshData** [comment]
What version of Python are you running? The package should be available at least since 3.5 (according to the Python docs).

**Comment by jacobcrp** [comment]
Thanks for getting back to me. Looks like the venv is running 2.7.12. Should we wipe this and start with 3.5+?

**Comment by JoshData** [comment]
Since October this project now uses Python 3, yeah.

**Comment by jacobcrp** [comment]
Great, working now. Thanks Josh!
