### ISSUE TITLE
Unable to scrape Committee meetings

### ISSUE THREAD

**Issue by trentmercer** [unitedstates/congress#272]
## Problem

* Running command ```./run committee_meetings --force --debug```
* Produces output similar to the following for each committee meeting: 
http://docs.house.gov/Committee/Calendar/ByEvent.aspx?EventID=111284
Problem downloading zipfile: 111284```

## Expected behavior

* Running command ```./run committee_meetings --force --debug``` downloads committee meetings as expected and creates both ```data/committee_meetings_house.json``` and ```data/committee_meetings_senate.json```

**Comment by JoshData** [comment]
Fixed, thanks.
