### ISSUE TITLE
Error in parsing sponsor & byRequest

### ISSUE THREAD

**Issue by aih** [unitedstates/congress#278]
In running the 'bills' scraper, I get an error on some bills from the 110th Congress which blocks further processing, due to missing `sponsor` in these lines:

https://github.com/unitedstates/congress/blob/28593b1e0ca91e1c85f9b2786c5336253b9a1c63/tasks/bills.py#L174
```
 'by_request': bill_dict['sponsors']['item'][0]['byRequestType']     is not None,
 'sponsor': bill_info.sponsor_for(bill_dict['sponsors']['item'][0]),
```

I am temporarily bypassing this in my local code by defining `by_request` and `sponsor` earlier in the code like this:

```
if bill_dict.get('sponsors') and bill_dict['sponsors'].get('item') and len(bill_dict['sponsors']['item']) > 0:
        sponsor = bill_info.sponsor_for(bill_dict['sponsors']['item'][0])
    else:
        sponsor = None
    
    byRequestTypeExists = sponsor and bill_dict['sponsors']['item'][0].get('requestType')
```

Is this a new issue? Am I doing something wrong in how I'm running the scraper?

**Comment by aih** [comment]
Unfortunately, I didn't log the info of which bills it failed on. But... I could make a PR if you think the solution above is reasonable.

**Comment by JoshData** [comment]
I think there might be something else going on. It's probably a "reserved" bill number without a sponsor, and for those we might be better to just skip them entirely. This happened around the same time on some current bills. I might have fixed it in https://github.com/unitedstates/congress/commit/28593b1e0ca91e1c85f9b2786c5336253b9a1c63.

**Comment by aih** [comment]
Probably so... I pulled your changes from 28593b1 after I had put in my changes above, so I wouldn't have seen whether the new commit fixes the issue. In any case, I'll close this issue, and will re-open if it comes back again.
