### ISSUE TITLE
Bulkdata download from sunlight foundation error

### ISSUE THREAD

**Issue by iita-atii** [unitedstates/congress#306]
I get the below error when trying to download bulkdata from the table on https://github.com/unitedstates/congress/wiki.

<img width="817" alt="Screenshot 2024-06-13 at 9 23 59 AM" src="https://github.com/unitedstates/congress/assets/99359152/e6bc207b-49ef-4dde-9f59-5fcbbf75cd1a">

It seems [ProPublica](https://www.propublica.org/datastore/dataset/congressional-data-bulk-legislation-bills) only has the XML available for bulk download. Is there another source for bulk JSON download or a way to use the existing sunlight foundation links?

**Comment by JoshData** [comment]
The Sunlight Foundation is unfortunately long gone (the organization doesn't exist anymore). @dwillis would know if there is alternative ProPublica data.

**Comment by DanielSchuman** [comment]
Can you share more about this information you wish to download?

The Government Publishing Office has some of this data published in bulk:
https://www.govinfo.gov/developers

**Comment by iita-atii** [comment]
Hey @DanielSchuman sorry for the delayed reply. 

I was hoping for JSON formatted bulk data but can do the xml to json conversion locally as well.
